### ISSUE TITLE
How does it work ?

### ISSUE THREAD

**Issue by berktaylan** [esign/laravel-conversions-api#10]
Does it use fbclid on somewhere when sending events ?

**Comment by jordyvanderhaegen** [comment]
This package currently sends the _fbc cookie to the Conversions API, with the caveat that it's not available in the initial request—only in subsequent ones. I welcome PRs to address this limitation by manually creating and sending the _fbc cookie with the initial request. Refer to [Facebook's documentation](https://developers.facebook.com/docs/marketing-api/conversions-api/parameters/fbp-and-fbc/#fbc) for guidance.
