### ISSUE TITLE
PageView event being reported as a Custom Event

### ISSUE THREAD

**Issue by paul-adams-985** [esign/laravel-conversions-api#13]
**Great package :)**

Could you please help me.

My page views are showing as custom events in the Event Manager.
See below:

![Events-Manager](https://github.com/user-attachments/assets/05a5150d-f5c8-4b4f-8198-331fa4fef75f)

**Here is the generated script:**

<script >
  fbq('track', 'PageView', {}, {"eventID":"da1529a3-bd33-4180-ac05-37c2dc368796"});
  </script>

  <script >
  fbq('track', 'PageView', {}, {"eventID":"da1529a3-bd33-4180-ac05-37c2dc368796"});
  </script>            
</body>

Have I made an error?
Huge thanks in advance
Paul

**Comment by jordyvanderhaegen** [comment]
Hi, it seems like that's the default behavior of the event testing tool.
PageView events appear to show up as custom events, even when using the [base code](https://developers.facebook.com/docs/meta-pixel/get-started#base-code) from the documentation.
