### ISSUE TITLE
Example sending contents

### ISSUE THREAD

**Issue by neamtua** [esign/laravel-conversions-api#17]
I didn't see any example about setting contents in the documentation so I've just blindly set something up.

Can you tell me if this is correct or just give an example on how to use that feature?

```php
use FacebookAds\Object\ServerSide\Content;
$fbEventContents = [];
        foreach (\Gloudemans\Shoppingcart\Facades\Cart::content() as $row) {
            $fbEventContents[] = new Content([
                'product_id' => $row->options->has('sku') ? $row->options->sku : '',
                'quantity' => $row->qty,
                'item_price' => $row->price,
                'title' => $row->name
            ]);
        }
$fbEvent = InitiateCheckoutEvent::create()->setCustomData(
            (new CustomData())
                ->setContents($fbEventContents)
                ->setCurrency('RON')
                ->setNumItems(Cart::count())
                ->setValue(\Gloudemans\Shoppingcart\Facades\Cart::priceTotal())
        );
```

**Comment by jordyvanderhaegen** [comment]
Hi, we don't cover this in the documentation as it's part of underlying [Facebook Business SDK](https://github.com/facebook/facebook-php-business-sdk). Furthermore, you may use the [Server Test Events Tool](https://www.facebook.com/business/help/ServerTestEventsTool) to see if your events reach Facebook correctly. See the `test_code` config value of this package.
