### ISSUE TITLE
 DEPRECATED  Return type of FacebookAds\Object\ServerSide\UserData

### ISSUE THREAD

**Issue by emkcloud** [esign/laravel-conversions-api#2]
PHP 8.1.7 (cli) (built: Jun 25 2022 08:12:59) (NTS)
Laravel Framework 9.40.1
OS: Ubuntu 22.04.1 LTS x86_64

I think it should be the fact that you require the Facebook SDK 12.0 and should be the most updated.

![image](https://user-images.githubusercontent.com/5731295/202464514-1dc96def-9c49-4eea-bbd2-bcc598ee2c2f.png)

**Comment by jordyvanderhaegen** [comment]
Thanks! Fixed in [2.1.0](https://github.com/esign/laravel-conversions-api/releases/tag/2.1.0)
