### ISSUE TITLE
Help: Multiple pixels

### ISSUE THREAD

**Issue by jeffagostinho** [esign/laravel-conversions-api#3]
Hello,

I have a platform as a service very similar to a marketplace, I would like to know how to use it for multiple facebook pixels.

Basically in the rendering of a product how can I load the facebook pixel dynamically, according to the owner of the product?

Congrats on the job,

Hugs

**Comment by jordyvanderhaegen** [comment]
Having multiple pixels on a single page is currently not supported. Dynamically setting the pixel could be achieved by using `Config::set('conversions-api.pixel_id', 'your-pixel-id');` I suppose.

Feel free to send a PR that adds support for multiple pixels.

**Comment by sunshineflower10** [comment]
Hi,
it would really be a good upgrade to have possibility of multiple Pixel codes. At least to be able to send it as a parameters of sendEvents function.
