### ISSUE TITLE
Docs not clear

### ISSUE THREAD

**Issue by softail** [esign/laravel-conversions-api#4]
![image](https://github.com/esign/laravel-conversions-api/assets/16388315/597f7ca3-2b14-4174-b29f-da944d2120ab)

I am trying to use this package for the first time, but i don't understand where do i put these events?
For example i want to sent an event on all pages like so:
```php
ConversionsApi::addEvent(
    (new Event())->setEventName('PageView')->setEventId((string) Str::uuid())
);
```

**Comment by jordyvanderhaegen** [comment]
Hi, this package ships with a built-in solution to track PageViews, see the [docs](https://github.com/esign/laravel-conversions-api#pageview-events).
