### ISSUE TITLE
Feature Request: Publishable Views

### ISSUE THREAD

**Issue by RauchenwaldC** [esign/laravel-conversions-api#6]
We are using Iubenda to ensure compliance with EU and other regulations and as such have to change the `<script>` tags to something like `<script type="text/plain" class="_iub_cs_activate-inline" data-iub-purposes="4">` in all views, which we are doing right now through patches.

It would be great if we could publish the views and simply make those modifications there.

**Comment by jordyvanderhaegen** [comment]
Available in [2.3.0](https://github.com/esign/laravel-conversions-api/releases/tag/2.3.0).
You may also pass component attributes instead of publishing the views
