### ISSUE TITLE
Sending events not working

### ISSUE THREAD

**Issue by aliwesome** [esign/laravel-conversions-api#7]
I use this package in order to get benefits of its integration with Facebook Conversion API, so I just use it to set custom events with custom data on my API to be triggered. 

So is there any one using this package that way?

I faced some issues regarding `ConversionsApi::sendEvents()` method, it seems like there's no response for this.

**Comment by jordyvanderhaegen** [comment]
The `sendEvents` method return an instance of `GuzzleHttp\Promise\PromiseInterface`, see the [Guzzle docs](https://docs.guzzlephp.org/en/stable/quickstart.html#async-requests) for more information. Feel free to reopen an issue if this is an actual problem with the package itself.
